def main()
    print("Asistencia para taller de Git 2024-2025S1:")
    print("1. Diego A. Estrada Rivera")
    print("2. El Perro")
    print("3. El Goat")
    print("4. Yadriel :)")
    print("5. AngelD.")
    print("\n")
    print("Asistencia para taller de Git 2024-2025S2:")
    print("1. Diego A. Estrada Rivera")
    print("2. Prueba prueba")
    print("3. El Gato")
main()

